import estillAlborz from '../assets/img/companies/لوگو سازمان 92.jpg';
import eEntekhab from '../assets/img/companies/entekhabE.jpeg';
import alibaba from '../assets/img/companies/alibaba.jpg';
import digikala from '../assets/img/companies/digiKala.jpg';
import bimeAseman from '../assets/img/companies/bimesaman.jpg';
import croose from '../assets/img/companies/croose.png';
import hamkaranSystem from '../assets/img/companies/hamkaranSystem.jpg'
import hamrahAval from '../assets/img/companies/hamrahaval.jpg';
import huawei from '../assets/img/companies/huaview.png';
import kaleh from '../assets/img/companies/kaleh.jpg';
import lootoos from '../assets/img/companies/lootoos.jpg';
import nanoAlvand from '../assets/img/companies/nanoAlvand.jpg';
import nilper from '../assets/img/companies/nilper.jpg';
import ofoghTolidDaroo from '../assets/img/companies/ofoghTolidDaroo.png';
import petroPars from '../assets/img/companies/petroPars.jpg'
import snapp from '../assets/img/companies/snapp.jpg';
import takmakaron from '../assets/img/companies/takMakaron.jpg';
import vatanZarin from '../assets/img/companies/vatanZarin.jpg';
import yektanet from '../assets/img/companies/yektanet.jpg';

export const offersList = [
  {
    id: 2256,
    title: "منشی مدیرعامل",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: false,
    daysPast: 9,
    location: "تهران - پونک",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 6589,
    title: "برنامه نویس فرانت اند",
    icon: digikala,
    companyName: "دیجی کالا",
    adaptive: false,
    daysPast: 12,
    location: "تهران - جردن",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 9925,
      title: "junior front-end developer",
    icon: snapp,
    companyName: "اسنپ",
    adaptive: true,
    daysPast: 0,
    location: "تهران - جردن",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 3345,
    title: "متخصص دواپس",
    icon: yektanet,
    companyName: "یکتانت",
    adaptive: true,
    daysPast: 49,
    location: "تهران - جردن",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 85789,
    title: "برنامه نویس فرانت-اند",
    icon: kaleh,
    companyName: "گروه کاله",
    adaptive: false,
    daysPast: 12,
    location: "تهران - ستارخان",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 9571,
    title: "برنامه نویس بک اند",
    icon: digikala,
    companyName: "دیجی کالا",
    adaptive: true,
    daysPast: 9,
    location: "تهران - جردن",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 225658,
    title: "کارشناس حقوقی",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: false,
    daysPast: 1,
    location: "تهران - یوسف آباد",
    salaryScaleId: 2,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 885288,
    title: "خلبان هواپیما",
    icon: alibaba,
    companyName: "علی بابا",
    adaptive: false,
    daysPast: 12,
    location: "تهران - یوسف آباد",
    salaryScaleId: 5,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 51151,
    title: "متخصص سیمکارت",
    icon: hamrahAval,
    companyName: "همراه اول",
    adaptive: false,
    daysPast: 6,
    location: "تهران - جردن",
    salaryScaleId: 2,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 5151,
      title: "senior back-end developer",
    icon: snapp,
    companyName: "اسنپ",
    adaptive: false,
    daysPast: 9,
    location: "تهران - پونک",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 5151,
    title: "گرافیک دیزاینر",
    icon: yektanet,
    companyName: "یکتانت",
    adaptive: false,
    daysPast: 6,
    location: "تهران - پاسداران",
    salaryScaleId: 2,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 26255,
    title: "کارشناس بازاریابی",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: false,
    daysPast: 12,
    location: "تهران - پونک",
    salaryScaleId: 5,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 62629854,
    title: "مدیر تکنولوژی",
    icon: digikala,
    companyName: "دیجی کالا",
    adaptive: false,
    daysPast: 49,
    location: "مازندران - ساری",
    salaryScaleId: 5,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 45418,
    title: "مدل جدید برای علی بابا",
    icon: alibaba,
    companyName: "علی بابا",
    adaptive: false,
    daysPast: 1,
    location: "تهران - جردن",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 151522,
    title: "مهندس شیمی",
    icon: petroPars,
    companyName: "پترو پارس",
    adaptive: false,
    daysPast: 9,
    location: "قزوین",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 55151,
    title: "حسابدار",
    icon: hamkaranSystem,
    companyName: "همکاران سیستم",
    adaptive: false,
    daysPast: 12,
    location: "تهران - پونک",
    salaryScaleId: 2,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },

  {
    id: 5151,
      title: "senior business developer",
    icon: snapp,
    companyName: "اسنپ",
    adaptive: true,
    daysPast: 4,
    location: "تهران - ستارخان",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[2],
  },
  {
    id: 62645,
    title: "کارشناس فروش",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: true,
    daysPast: 20,
    location: "تهران - جردن",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 5151,
    title: "جونیور بیزینس دولوپر",
    icon: digikala,
    companyName: "دیجی کالا",
    adaptive: true,
    daysPast: 12,
    location: "مازندران - ساری",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 62655852,
    title: "جونیور همراه برای اول",
    icon: hamrahAval,
    companyName: "همراه اول",
    adaptive: false,
    daysPast: 0,
    location: "تهران - شیخ بهایی",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[2],
  },
  {
    id: 515151,
    title: " فروش",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: true,
    daysPast: 20,
    location: "تهران - پونک",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 554154,
    title: "تیستر غذا",
    icon: takmakaron,
    companyName: "تک ماکارون",
    adaptive: false,
    daysPast: 4,
    location: "تهران - جردن",
    salaryScaleId: 2,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 45612,
      title: "android developer",
    icon: snapp,
    companyName: "اسنپ",
    adaptive: false,
    daysPast: 12,
    location: "تهران - پاسداران",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 26252,
    title: " فروش",
    icon: estillAlborz,
    companyName: "استیل البرز",
    adaptive: false,
    daysPast: 1,
    location: "تهران - ستارخان",
    salaryScaleId: 3,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 515151,
    title: "راننده وانت",
    icon: digikala,
    companyName: "دیجی کالا",
    adaptive: true,
    daysPast: 6,
    location: "تهران - یوسف آباد",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 515120,
    title: "مدیر بازاریابی",
    icon: nilper,
    companyName: "گروه نیلپر",
    adaptive: true,
    daysPast: 6,
    location: "تهران - ستارخان",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[2],
  },
  {
    id: 11111,
    title: "کارمند مرکز تماس",
    icon: kaleh,
    companyName: "گروه کاله",
    adaptive: false,
    daysPast: 12,
    location: "تهران - جردن",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 3324234,
    title: "مهندس نفت",
    icon: petroPars,
    companyName: "پترو پارس",
    adaptive: false,
    daysPast: 4,
    location: "مازندران - ساری",
    salaryScaleId: 3,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },
  {
    id: 234234,
    title: "کارشناس همراهی",
    icon: hamrahAval,
    companyName: "همراه اول",
    adaptive: false,
    daysPast: 0,
    location: "تهران - پاسداران",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },
  {
    id: 234235,
    title: "مدیر فروش",
    icon: nilper,
    companyName: "گروه نیلپر",
    adaptive: false,
    daysPast: 49,
    location: "تهران - شیخ بهایی",
    salaryScaleId: 4,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
  {
    id: 3453452,
    title: "متخصص تغذیه",
    icon: takmakaron,
    companyName: "تک ماکارون",
    adaptive: false,
    daysPast: 1,
    location: "تهران - شیخ بهایی",
    salaryScaleId: 3,
    featureIds: [],
    categoryId: 12,
    jobForms:[2],
  },{
    id: 3453452,
    title: "متخصص وکالت",
    icon: hamkaranSystem,
    companyName: "همکاران سیستم",
    adaptive: false,
    daysPast: 12,
    location: "تهران - جردن",
    salaryScaleId: 5,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },{
    id: 23523,
    title: "مدرس زبان انگلیسی",
    icon: kaleh,
    companyName: "گروه کاله",
    adaptive: false,
    daysPast: 4,
    location: "تهران - یوسف آباد",
    salaryScaleId: 3,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3],
  },{
    id: 235235,
    title: "کارشناس بیمه",
    icon: bimeAseman,
    companyName: "بیمه آسمان",
    adaptive: true,
    daysPast: 20,
    location: "قزوین",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0, 3, 2, 1],
  },{
    id: 2352353,
    title: "مدیر تکنولوژی",
    icon: nilper,
    companyName: "گروه نیلپر",
    adaptive: false,
    daysPast: 6,
    location: "تهران - پاسداران",
    salaryScaleId: 5,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },{
    id: 123123,
    title: "متخصص تولید محتوا",
    icon: takmakaron,
    companyName: "تک ماکارون",
    adaptive: true,
    daysPast: 0,
    location: "تهران - شیخ بهایی",
    salaryScaleId: 0,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },{
    id: 345234,
    title: "بازاریاب میدانی",
    icon: hamkaranSystem,
    companyName: "همکاران سیستم",
    adaptive: false,
    daysPast: 4,
    location: "تهران - جردن",
    salaryScaleId: 1,
    featureIds: [],
    categoryId: 12,
    jobForms:[1],
  },{
    id: 546345,
    title: "کارشناس حقوقی",
    icon: bimeAseman,
    companyName: "بیمه آسمان",
    adaptive: false,
    daysPast: 1,
    location: "تهران - پونک",
    salaryScaleId: 3,
    featureIds: [],
    categoryId: 12,
    jobForms:[0,],
  },
];
